### ISSUE TITLE
UIAState not sent properly through WebSocket

### ISSUE THREAD

**Issue by djfigs1** [SUITS-Techteam/TSS#39]
In the browser view, when activating UIA Telemetry, you can manipulate the switches and see the values change. However, using the Unity plugin (and the WebSocket by extension), it always reads as the following:

```json
"uiaState": {
        "emu1_is_booted": false,
        "uia_supply_pressure": 0.0,
        "water_level": 0.0,
        "airlock_pressure": 0.0,
        "depress_pump_fault": false
}
```

As such, it is impossible to tell from the Unity plugin what the UIA Telemetry is.

**Comment by ObjectJosh** [comment]
Is this still an issue after following the release notes? https://github.com/SUITS-Techteam/TSS/releases/tag/v3.0.0-teams

**Comment by djfigs1** [comment]
Yes it is, I apologize for not setting that earlier.
